ALTER TABLE .user 
CHANGE COLUMN email email VARCHAR(45) NOT NULL AFTER id,
ADD COLUMN name VARCHAR(45) NOT NULL AFTER password,
ADD COLUMN surname VARCHAR(45) NOT NULL AFTER name,
ADD COLUMN male VARCHAR(45) NOT NULL AFTER surname;
