ALTER TABLE author 
ADD COLUMN UUID VARCHAR(45) NOT NULL AFTER id;
ALTER TABLE publisher 
ADD COLUMN UUID VARCHAR(45) NOT NULL AFTER id;
ALTER TABLE book 
ADD COLUMN UUID VARCHAR(45) NOT NULL AFTER id;

