ALTER TABLE `mydb`.`author` 
ADD COLUMN `UUiD` VARCHAR(45) NOT NULL AFTER `id`;
ALTER TABLE `mydb`.`publisher` 
ADD COLUMN `UUiD` VARCHAR(45) NOT NULL AFTER `id`;
ALTER TABLE `mydb`.`book` 
ADD COLUMN `UUiD` VARCHAR(45) NOT NULL AFTER `id`;

