ALTER TABLE author 
CHANGE COLUMN UUID UUID VARCHAR(36) NOT NULL ;
ALTER TABLE book 
CHANGE COLUMN UUID UUID VARCHAR(36) NOT NULL ;
ALTER TABLE publisher 
CHANGE COLUMN UUID UUID VARCHAR(36) NOT NULL ;
