ALTER TABLE `mydb`.`author` 
CHANGE COLUMN `UUiD` `UUID` VARCHAR(45) NOT NULL ;
ALTER TABLE `mydb`.`book` 
CHANGE COLUMN `UUiD` `UUID` VARCHAR(45) NOT NULL ;
ALTER TABLE `mydb`.`publisher` 
CHANGE COLUMN `UUiD` `UUID` VARCHAR(45) NOT NULL ;
