ALTER TABLE `mydb`.`author` 
CHANGE COLUMN `UUiD` `UUiD` VARCHAR(36) NOT NULL ;
ALTER TABLE `mydb`.`book` 
CHANGE COLUMN `UUiD` `UUiD` VARCHAR(36) NOT NULL ;
ALTER TABLE `mydb`.`publisher` 
CHANGE COLUMN `UUiD` `UUiD` VARCHAR(36) NOT NULL ;
